//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int d_Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public Nullable<double> Phone { get; set; }
        public string Working_Days { get; set; }
    }
}
